### ISSUE TITLE
Unable to make it work in React

### ISSUE THREAD

**Issue by newbster1** [mariohamann/bento-grid.js#1]
https://codesandbox.io/p/devbox/zrf4yy?migrateFrom=95h8rz&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltyknuq600063b6hg9oeilsf%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltyknuq600023b6hfspummvf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltyknuq600043b6h4w87y9et%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltyknuq600053b6h92t7cry7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltyknuq600023b6hfspummvf%2522%253A%257B%2522id%2522%253A%2522cltyknuq600023b6hfspummvf%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltyknuq600053b6h92t7cry7%2522%253A%257B%2522id%2522%253A%2522cltyknuq600053b6h92t7cry7%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltyknuq600043b6h4w87y9et%2522%253A%257B%2522id%2522%253A%2522cltyknuq600043b6h4w87y9et%2522%252C%2522activeTabId%2522%253A%2522cltykz9r100wt3b6hfdqorcsj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltyknuq600033b6h7a0uddjp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltyknv26000bdaf874eg6eni%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522cltykz9r100wt3b6hfdqorcsj%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

Here is code sandbox link as well, if you can assist with how to make it work in react

**Comment by newbster1** [comment]
hello @mariohamann  can you please assist

**Comment by mariohamann** [comment]
Hey,

here's an example: https://stackblitz.com/edit/vite-react-tailwind-uiq5z4?file=src%2FApp.jsx

Everything working fine here.

Please provide a working minimal example next time – in you're example just code from my docs src files was copied, the Bentogrid component wasn't called and @bentogrid/core wasn't even installed.
