### ISSUE TITLE
Bentogird is unevenly distributed

### ISSUE THREAD

**Issue by veridynn** [mariohamann/bento-grid.js#2]
**Browser:** LibreWolf (fork of Firefox)
**Framework:** Vue3/Nuxt

**Code Implementation:**
```js
<script setup lang="ts">
import BentoGrid from "@bentogrid/core";

onMounted(() => {
  new BentoGrid({
    cellGap: 12,
    columns: 2,
    breakpoints: {
      640: {
        columns: 4,
        cellGap: 18
      }
    }
  });
})
</script>
```
```html
<template>
  <div class="bentogrid">
    <slot></slot>
  </div>
</template>
```
**Issues:**
1. **Grid Distribution:**
    The grid is not distributed evenly. I am unsure if this is due to an implementation error on my part or a potential bug in the library. Below is an image illustrating the issue:
    <img width="1649" alt="image" src="https://github.com/mariohamann/bentogrid.js/assets/35661226/cae1de17-ae1d-4200-991c-1bbf0e6a03bc">

1. **Performance (CLS):**
The grid takes approximately 1000ms to be created, causing a significant Cumulative Layout Shift (CLS). Any suggestions for improvement would be appreciated. If not, I plan to mitigate this by rendering the grid server-side.

Thank you for your assistance.

**Comment by mariohamann** [comment]
Hey there! Could you please create a reproduction e.g. on Stackblitz or similar? Thanks!

**Comment by veridynn** [comment]
While reproducing the bug, I noticed that the grid is evenly distributed and the aspect ratio is correct when the tiles are empty. However, as soon as text or child elements are added, the issue arises, worsening with more content.

Here are the links to the reproduction on Stackblitz:
- [Code](https://stackblitz.com/edit/nuxt-starter-durpvk?file=pages%2Findex.vue&view=editor) 
- [Preview](https://nuxtstarterdurpvk-jc03--3000--71ef666c.local-corp.webcontainer.io/)

Thank you for looking into this.

**Comment by mariohamann** [comment]
Thanks for the links:

I [forked](https://stackblitz.com/edit/nuxt-starter-eiww8q?file=components%2FBentoGrid.vue&view=editor) it, added some cheap `console.logs` and what I see is: 

![CleanShot 2024-05-28 at 07 32 25@2x](https://github.com/mariohamann/bentogrid.js/assets/26542182/a65d8cae-9100-4f7a-a026-662c5dae2702)

Between mounting the component and calculating the Bentogrid there are 0ms–1ms.I did a production build and there the lag is MUCH shorter. Therefore I believe this especially comes from how bundling is handled in dev mode.

---

Regarding content: If the content doesn't fit the grid, of course the grid could break out. You should really plan your tiles coming from how much content you serve. I think the example on https://bentogrid.mariohamann.com/ gives you a quite good sense how to plan the sizes of your tiles.

Does that help you?

**Comment by veridynn** [comment]
Yes, this helps for now. I'll continue with my project and try to solve the calculation issue along the way. We can close the ticket for now but I might get back to you with more details if you don't mind.

I appreciate your help!

**Comment by mariohamann** [comment]
Great!
